<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>fileTypes</key>
		<array>
			<string>liquid</string>
		</array>
		<key>name</key>
		<string>HTML (Liquid)</string>
		<key>patterns</key>
		<array>
			<dict>
				<key>begin</key>
				<string>{% comment %}</string>
				<key>end</key>
				<string>{% endcomment %}</string>
				<key>name</key>
				<string>comment.block.liquid</string>
			</dict>
			<dict>
				<key>begin</key>
				<string>{{</string>
				<key>end</key>
				<string>}}</string>
				<key>name</key>
				<string>meta.type.variable.liquid</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#template_var</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>begin</key>
				<string>{%</string>
				<key>end</key>
				<string>%}</string>
				<key>name</key>
				<string>punctuation.type.variable.liquid</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#template_tag_name</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#template_var</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>begin</key>
				<string>{%\s*(capture)\s*%}</string>
				<key>captures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>keyword.tag.liquid</string>
					</dict>
				</dict>
				<key>end</key>
				<string>{%\s*endcapture\s*%}</string>
				<key>name</key>
				<string>storage.type.templatetag.liquid</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#template_var</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#template_tag</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#template_filter</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>begin</key>
				<string>{%\s*for</string>
				<key>captures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>keyword.tag.liquid</string>
					</dict>
				</dict>
				<key>end</key>
				<string>%}</string>
				<key>name</key>
				<string>storage.type.logictag.liquid</string>
				<key>patterns</key>
				<array>
					<dict>
						
					</dict>
					<dict>
						<key>match</key>
						<string>\s+in\s+</string>
						<key>name</key>
						<string>keyword.operator.logical.liquid</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#template_var</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>begin</key>
				<string>{%\s*assign</string>
				<key>captures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>keyword.tag.liquid</string>
					</dict>
				</dict>
				<key>end</key>
				<string>%}</string>
				<key>name</key>
				<string>storage.type.assigntag.liquid</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#assign_op</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#template_var</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>match</key>
				<string>({%)?(?=\s*)(?![\.0-9])[a-zA-Z0-9_-]+(?=\s*)(%})?</string>
				<key>name</key>
				<string>keyword.tag.tagbraces.liquid</string>
			</dict>
			<dict>
				<key>include</key>
				<string>text.html.basic</string>
			</dict>
		</array>
		<key>repository</key>
		<dict>
			<key>template_tag_name</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>(?&lt;={%)\s*(\w+)</string>
						<key>name</key>
						<string>entity.name.tag.liquid</string>
					</dict>
				</array>
			</dict>
			<key>logic_op</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>\s+(and|or|not|contains|((\!|\=|&lt;|&gt;)\=))\s+</string>
						<key>name</key>
						<string>keyword.operator.logical.liquid</string>
					</dict>
				</array>
			</dict>
			<key>assign_op</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>/=</string>
						<key>name</key>
						<string>keyword.operator.assignment.augmented.liquid</string>
					</dict>
				</array>
			</dict>
			<key>template_var</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>(false|true)</string>
						<key>name</key>
						<string>constant.language.liquid</string>
					</dict>
					<dict>
						<key>match</key>
						<string>\s+(and|or|not|contains|in|((\!|\=|&lt;|&gt;)\=))\s+</string>
						<key>name</key>
						<string>keyword.operator.liquid</string>
					</dict>
					<dict>
						<key>match</key>
						<string>\|\s+(?![\.0-9])[a-zA-Z0-9_-]+\:\s+</string>
						<key>name</key>
						<string>support.function.with-args.liquid</string>
					</dict>
					<dict>
						<key>match</key>
						<string>\|\s+(?![\.0-9])[a-zA-Z0-9_-]+\s+</string>
						<key>name</key>
						<string>support.function.without-args.liquid</string>
					</dict>
					<dict>
						<key>begin</key>
						<string>"</string>
						<key>end</key>
						<string>"</string>
						<key>name</key>
						<string>string.quoted.double.liquid</string>
					</dict>
					<dict>
						<key>begin</key>
						<string>'</string>
						<key>end</key>
						<string>'</string>
						<key>name</key>
						<string>string.quoted.single.liquid</string>
					</dict>
					<dict>
						<key>match</key>
						<string>(-|\+)?\s*[0-9]+(\.[0-9]+)?</string>
						<key>name</key>
						<string>constant.numeric.liquid</string>
					</dict>
					<dict>
						<key>match</key>
						<string>\b(collection|product|linklist|linklists|order|link|customer|customer_address|line_item|shop|collections|page_title|template|image|blog|blogs|cart|pages|theme|themes|variant|items|comment)\b</string>
						<key>name</key>
						<string>support.class.liquid</string>
					</dict>
					<dict>
						<key>match</key>
						<string>(?&lt;=\:\s)(\w+)(?=\s*\|)</string>
						<key>end</key>
						<string>\]</string>
						<key>name</key>
						<string>variable.parameter.filter-arg.liquid</string>
					</dict>
					<dict>
						<key>match</key>
						<string>\[(\w+)\]</string>
						<key>end</key>
						<string>\]</string>
						<key>name</key>
						<string>variable.other.liquid</string>
					</dict>
					<dict>
						<key>match</key>
						<string>(?&lt;=\.)\w+\b</string>
						<key>name</key>
						<string>entity.other.attribute-name.liquid</string>
					</dict>
					<dict>
						<key>match</key>
						<string>\w+</string>
						<key>name</key>
						<string>variable.other.liquid</string>
					</dict>
				</array>
			</dict>
		</dict>
		<key>scopeName</key>
		<string>text.html.liquid</string>
	</dict>
</plist>
