<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>fileTypes</key>
		<array>
			<string>liquid</string>
		</array>
		<key>name</key>
		<string>HTML (Liquid)</string>
		<key>patterns</key>
		<array>
			<dict>
				<key>begin</key>
				<string>{% comment %}</string>
				<key>end</key>
				<string>{% endcomment %}</string>
				<key>name</key>
				<string>comment.block.liquid</string>
			</dict>
			<dict>
				<key>begin</key>
				<string>{{</string>
				<key>captures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>punctuation.braces.liquid</string>
					</dict>
				</dict>
				<key>end</key>
				<string>}}</string>
				<key>name</key>
				<string>storage.type.variable.liquid</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#template_var</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>begin</key>
				<string>{%\s*(cycle|include|tablerow|case|when|raw|form)</string>
				<key>captures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>keyword.tag.tagbraces.liquid</string>
					</dict>
				</dict>
				<key>end</key>
				<string>%}</string>
				<key>name</key>
				<string>storage.type.templatetag.liquid</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#template_tag</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#template_filter</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>begin</key>
				<string>{%\s*capture</string>
				<key>captures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>keyword.tag.liquid</string>
					</dict>
				</dict>
				<key>end</key>
				<string>%}</string>
				<key>name</key>
				<string>storage.type.templatetag.liquid</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#template_tag</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#template_filter</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>begin</key>
				<string>{%\s*for</string>
				<key>captures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>keyword.tag.liquid</string>
					</dict>
				</dict>
				<key>end</key>
				<string>%}</string>
				<key>name</key>
				<string>storage.type.logictag.liquid</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>begin</key>
						<string>\(</string>
						<key>captures</key>
						<dict>
							<key>0</key>
							<dict>
								<key>name</key>
								<string>punctuation.separator.loopindex.liquid</string>
							</dict>
						</dict>
						<key>end</key>
						<string>\)</string>
						<key>name</key>
						<string>storage.type.fortag.liquid</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>match</key>
								<string>(\.\.)</string>
								<key>name</key>
								<string>keyword.operator.logical.liquid</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#assign_op</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#template_var</string>
							</dict>
						</array>
					</dict>
					<dict>
						<key>match</key>
						<string>\s+in\s+</string>
						<key>name</key>
						<string>keyword.operator.logical.liquid</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#template_var</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>begin</key>
				<string>{%\s*(if|elsif|unless)</string>
				<key>captures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>keyword.tag.liquid</string>
					</dict>
				</dict>
				<key>end</key>
				<string>%}</string>
				<key>name</key>
				<string>storage.type.logictag.liquid</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#logic_op</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#template_var</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#template_tag</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#template_filter</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>begin</key>
				<string>{%\s*assign</string>
				<key>captures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>keyword.tag.liquid</string>
					</dict>
				</dict>
				<key>end</key>
				<string>%}</string>
				<key>name</key>
				<string>storage.type.assigntag.liquid</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#assign_op</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#template_var</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>match</key>
				<string>{%\s*(endfor|endif|else|endunless|endtablerow|endcase|endraw|endcapture|endform)\s*%}</string>
				<key>name</key>
				<string>keyword.tag.tagbraces.liquid</string>
			</dict>
			<dict>
				<key>include</key>
				<string>text.html.basic</string>
			</dict>
		</array>
		<key>repository</key>
		<dict>
			<key>template_filter</key>
			<dict>
				<key>patterns</key>
				<array>
				</array>
			</dict>
			<key>logic_op</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>\s+(and|or|not|contains|((\!|\=|&lt;|&gt;)\=))\s+</string>
						<key>name</key>
						<string>keyword.operator.logical.liquid</string>
					</dict>
				</array>
			</dict>
			<key>assign_op</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>/=</string>
						<key>name</key>
						<string>keyword.operator.assignment.augmented.liquid</string>
					</dict>
				</array>
			</dict>
			<key>template_var</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>(false|true)</string>
						<key>name</key>
						<string>support.constant.property-value</string>
					</dict>
					<dict>
						<key>match</key>
						<string>\|\s+(?![\.0-9])[a-zA-Z0-9_-]+:\s+\b</string>
						<key>name</key>
						<string>keyword.method.with-arguments.liquid</string>
					</dict>
					<dict>
						<key>match</key>
						<string>\|\s+(?![\.0-9])[a-zA-Z0-9_-]+\s+\b</string>
						<key>name</key>
						<string>keyword.method.with-arguments.liquid</string>
					</dict>
					<dict>
						<key>begin</key>
						<string>"</string>
						<key>end</key>
						<string>"</string>
						<key>name</key>
						<string>string.quoted.single.liquid</string>
					</dict>
					<dict>
						<key>match</key>
						<string>(\[|\.)+((?![\.0-9])[a-zA-Z0-9_-]+)(\]|\.)+</string>
						<key>name</key>
						<string>support.type.property-name.liquid</string>
					</dict>
					<dict>
						<key>captures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>entity.other.attribute-name.class.liquid</string>
							</dict>
							<key>2</key>
							<dict>
								<key>name</key>
								<string>punctuation.separator.variable.liquid</string>
							</dict>
							<key>3</key>
							<dict>
								<key>name</key>
								<string>support.type.property-name.liquid</string>
							</dict>
							<key>4</key>
							<dict>
								<key>name</key>
								<string>punctuation.separator.variable.liquid</string>
							</dict>
						</dict>
						<key>match</key>
						<string>\[((?![\.0-9])[a-zA-Z0-9_-]+)\]</string>
						<key>name</key>
						<string>variable.array-index-name.liquid</string>
					</dict>
					<dict>
						<key>match</key>
						<string>(-|\+)?\s*[0-9]+(\.[0-9]+)?</string>
						<key>name</key>
						<string>constant.numeric.css</string>
					</dict>
					<dict>
						<key>match</key>
						<string>((?![\.0-9])[a-zA-Z0-9_-]+)</string>
						<key>name</key>
						<string>punctuation.definition.variable.liquid</string>
					</dict>
				</array>
			</dict>
		</dict>
		<key>scopeName</key>
		<string>text.html.liquid</string>
	</dict>
</plist>
